name: audio_relay_x_server
description: Fully Open Source Local Network Audio Relay
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  bootstrap:
    git:
      url: https://github.com/AudioRelayXX/app_bootstrap
      ref: master
  trebuchet:
    git:
      url: https://github.com/AudioRelayXX/trebuchet
      ref: master
  flywheel:
    git:
      url: https://github.com/AudioRelayXX/flywheel
      ref: master
  forge:
    git:
      url: https://github.com/AudioRelayXX/forge
      ref: master
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.5
  flutter_pcm_sound: ^3.3.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  opus_flutter_windows:
    git:
      url: https://github.com/AudioRelayXX/opus_flutter.git
      ref: master
      path: opus_flutter_windows
  flutter_pcm_sound:
    git:
      url: https://github.com/AudioRelayXX/flutter_pcm_sound_windows.git
      ref: master


flutter:
  uses-material-design: true